# Theoretical Questions:

# Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

It was designed to handle large datasets and perform numerical computations efficiently, making it fundamental for tasks in fields like data science, machine learning, physics, engineering, and more. 

1. Efficient Multidimensional Arrays

2. Fast Computation

3. Extensive Mathematical Functions for operations like linear algebra, statistical analysis, Fourier transforms, and more.

5. Simplified Code and Improved Readability

In [1]:
# Using lists for element-wise addition
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = [x + y for x, y in zip(list1, list2)]
print(result)

[5, 7, 9]


In [2]:
# With NumPy, this operation becomes simpler and faster:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2  # Vectorized addition
print(result)

[5 7 9]


# Q.2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean() when:

You need a straightforward arithmetic mean without any weights.
You prefer a slightly faster computation (since np.mean() is optimized for unweighted averages).

np.average() when:

You need to compute a weighted average.
You want the flexibility to return the sum of weights alongside the average for further analysis.

In [3]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
np.mean(array)  

3.0

In [4]:
array = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 0.5, 1, 0.5, 1])
np.average(array, weights=weights)

3.0

# Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy array can be done efficiently using slicing and specific functions. 

For 1D arrays: Use slicing [::-1] to reverse the order.

For 2D arrays:
Use slicing [::-1, :] or [:, ::-1] to reverse along specific axes.

Use np.flip() to reverse along specified axes or both.

In [5]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_array_1d = array_1d[::-1]
print(reversed_array_1d)

[5 4 3 2 1]


In [6]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

reversed_rows = array_2d[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Q.4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [7]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3])

# Check the data type
print(array.dtype)

int32


Importance of Data Types in Memory Management and Performance-

Memory Management-

Efficient Storage: NumPy arrays are homogeneously typed, meaning all elements share the same data type. This allows them to be stored more compactly in memory than Python lists, which can hold mixed types.

Memory Footprint: The data type of an array affects how much memory it uses. For instance, an array of int32 (32-bit integers) consumes half the memory of an int64 (64-bit integers) array, which can be critical when working with large datasets.


In [8]:
array_int32 = np.array([1, 2, 3], dtype=np.int32)  # Uses 4 bytes per element
array_int64 = np.array([1, 2, 3], dtype=np.int64)  # Uses 8 bytes per element

Performance-

Computation Speed: Smaller data types (e.g., int8, float32) generally allow faster calculations compared to larger types (e.g., int64, float64) due to less memory access per operation. Smaller data types also enable more data to fit into the CPU cache, enhancing performance in large computations.

Vectorized Operations: NumPy’s operations are optimized for specific data types, especially those that match the underlying hardware. For instance, using float32 on a GPU or SIMD-enabled CPU can speed up computation compared to float64.

# Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarrays are more memory-efficient, faster, and better suited for numerical and scientific computations than standard Python lists, thanks to their homogeneous data type, support for multi-dimensional structures, and rich set of mathematical operations.

In [9]:
import numpy as np

# Python list
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
result_list = [x + y for x, y in zip(list_1, list_2)]  # Loop required for element-wise addition

# NumPy ndarray
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
result_array = array_1 + array_2 

In [10]:
print(result_list)

[5, 7, 9]


In [11]:
print(result_array)

[5 7 9]


# Q.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to their specialized structure and optimization for numerical computing. Here are the main factors contributing to the performance advantages of NumPy arrays:

Faster computations: Vectorization and built-in functions lead to faster calculations.

Lower memory usage: Homogeneous data types and contiguous memory layout reduce memory footprint.

Better scalability: Broadcasting and integration with low-level libraries make it possible to handle complex, large-scale computations efficiently.

These advantages make NumPy a powerful tool for numerical operations and data processing, significantly outperforming Python lists in speed and memory efficiency when dealing with large datasets.

In [12]:
import numpy as np
import time

# Create a large list and a large NumPy array
list_data = list(range(1000000))
array_data = np.array(list_data)

# Python list - calculate square of each element
start_time = time.time()
list_result = [x**2 for x in list_data]
print("Python list time:", time.time() - start_time)

# NumPy array - calculate square of each element
start_time = time.time()
array_result = array_data**2
print("NumPy array time:", time.time() - start_time)

Python list time: 0.03900003433227539
NumPy array time: 0.0


# Q.7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

The vstack() and hstack() functions in NumPy are used for stacking (concatenating) arrays vertically and horizontally, respectively. These functions are especially useful for combining multiple arrays into a single array along a specific axis.

1. np.vstack()

Purpose: Stacks arrays vertically (row-wise) along a new row axis. This is typically used when you want to add rows to an existing array.

Requirements: The arrays being stacked must have the same number of columns (second dimension).
Behavior: It creates a new array with additional rows.

In [13]:
import numpy as np

# Define two 2D arrays with the same number of columns
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))
print(result_vstack)

#In this example, np.vstack() combines array1 and array2 by stacking array2 as new rows below array1.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2. np.hstack()

Purpose: Stacks arrays horizontally (column-wise) along a new column axis. This is typically used when you want to add columns to an existing array.

Requirements: The arrays being stacked must have the same number of rows (first dimension).
Behavior: It creates a new array with additional columns.

In [14]:
# Define two 2D arrays with the same number of rows
array3 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

array4 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

# Stack arrays horizontally
result_hstack = np.hstack((array3, array4))
print(result_hstack)

#In this example, np.hstack() combines array3 and array4 by adding array4 as new columns to the right of array3.

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


These stacking functions are commonly used for reshaping and merging datasets in data analysis, where each array represents data with matching dimensions along one axis.

# Q.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on variousarray dimensions.

The fliplr() and flipud() functions in NumPy are used to flip arrays along specific axes, providing a quick way to reverse the order of elements horizontally or vertically in a 2D array. Here’s a breakdown of their differences, behavior, and effects on arrays.

1. np.fliplr()
Purpose: Flips a 2D array left-to-right, reversing the order of columns.
Behavior: It reverses elements along the second dimension (horizontal axis) of the array, essentially reflecting it horizontally.
Effect: It only works on 2D arrays (or higher) and will raise an error if used on a 1D array.

In [15]:
import numpy as np

# Define a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flip the array left to right
result_fliplr = np.fliplr(array)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. np.flipud()
Purpose: Flips a 2D array up-to-down, reversing the order of rows.
Behavior: It reverses elements along the first dimension (vertical axis) of the array, effectively reflecting it vertically.
Effect: It works on 1D, 2D, and higher-dimensional arrays, reversing the order along the first axis.

In [16]:
# Using the same 2D array as above
result_flipud = np.flipud(array)
print(result_flipud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. This function is particularly useful when you need to partition an array into several pieces for processing or analysis.

Functionality of array_split()

Parameters:

ary: The input array to be split.

indices_or_sections: This can be an integer or a 1-D array-like object.
 
If it's an integer, it specifies the number of equal parts to split the array into.

If it's an array-like object, it defines the specific indices at which to split the array.

axis: The axis along which to split the array (default is 0).

Returns: A list of sub-arrays after splitting the original array.

Handling Uneven Splits
When splitting an array, array_split() intelligently handles cases where the number of elements does not divide evenly. Here's how it works:

Uneven Splits: If the total number of elements in the array cannot be evenly divided by the specified number of sections, NumPy will create the sub-arrays with as equal sizes as possible. The last sub-array will contain the remaining elements.

Integer Input: When providing an integer for the number of sections, array_split() will distribute the elements as evenly as possible across the specified number of sub-arrays. For instance, if you have 10 elements and you want to split them into 3 sections, you will get two sections of 3 elements and one section of 4 elements.

Array-like Input: If you specify an array of indices, the split will occur at those indices regardless of the number of elements in the resulting sub-arrays.

In [17]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
split_array = np.array_split(array, 3)
print(split_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
# Create another array
array_uneven = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 3 parts
split_array_uneven = np.array_split(array_uneven, 3)
print(split_array_uneven)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


# Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are powerful features of NumPy that facilitate efficient and expressive numerical computations. By leveraging these concepts, you can write code that is not only faster but also clearer and more concise, making it easier to work with complex datasets and perform advanced calculations.

# Practical Questions:

# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [19]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:")
print(array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

# Print the transposed array
print("\nTransposed Array (interchanged rows and columns):")
print(transposed_array)

Original Array:
[[89 37 56]
 [80 42 32]
 [47 46 91]]

Transposed Array (interchanged rows and columns):
[[89 80 47]
 [37 42 46]
 [56 32 91]]


# Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [20]:
import numpy as np

# Generate a 1D NumPy array with 10 elements (e.g., integers from 0 to 9)
array_1d = np.arange(10)

# Print the original 1D array
print("Original 1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Print the reshaped 2x5 array
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the reshaped 5x2 array
print("\nReshaped to 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Q.3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [21]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.random((4, 4))

# Print the original 4x4 array
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the original array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)

Original 4x4 Array:
[[0.69602698 0.92549123 0.68897172 0.56288414]
 [0.519802   0.31956007 0.50714628 0.42274228]
 [0.32170512 0.39535946 0.47661714 0.83156471]
 [0.28233281 0.24204203 0.72557315 0.04839433]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.69602698 0.92549123 0.68897172 0.56288414 0.        ]
 [0.         0.519802   0.31956007 0.50714628 0.42274228 0.        ]
 [0.         0.32170512 0.39535946 0.47661714 0.83156471 0.        ]
 [0.         0.28233281 0.24204203 0.72557315 0.04839433 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [22]:
# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array_integers)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [23]:
# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)

# Print the original array and the transformed arrays
print("Original Array:")
print(array_strings)

print("\nUppercase Array:")
print(uppercase_array)

print("\nLowercase Array:")
print(lowercase_array)

print("\nTitlecase Array:")
print(titlecase_array)

print("\nCapitalized Array:")
print(capitalize_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']

Capitalized Array:
['Python' 'Numpy' 'Pandas']


# Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [24]:
# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Print the original array and the transformed array
print("Original Array:")
print(array_words)

print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [25]:
# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]]

Element-wise Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [26]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the diagonal elements
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# Q 9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [27]:
def is_prime(num):
    """Check if a number is prime."""
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the random array and the prime numbers found
print("Random Array of 100 Integers:")
print(random_array)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array of 100 Integers:
[533 397 882 332 749  97 416 147 563 941 978 840 951 791 953 575 106 870
  86 946 532 135 813 872 256 107 208 746 790  41 569 938 416 837 804 522
  86 650 513 589 280 454 634 204 455 472 950 335 993  89 168 199 315 241
 989  73 153 922  36 752 302 818 611 382  66  21 819  60 389 522 879 145
 125 300 759 410 260 853 960 558 128  66 550 284 357 415  32 633 495 234
 941 884 630 544 165 331 200 375 713 648]

Prime Numbers in the Array:
[397, 97, 563, 941, 953, 107, 41, 569, 89, 199, 241, 73, 389, 853, 941, 331]


# Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [28]:
# Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, let's generate random temperatures between 0 and 35 degrees Celsius
daily_temperatures = np.random.uniform(0, 35, size=30)

# Print the daily temperatures
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array to represent weeks (4 weeks with 2 days)
# Here, we'll consider the first 28 days for 4 complete weeks
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the weekly averages
print("\nWeekly Average Temperatures:")
for week in range(4):
    print(f"Week {week + 1}: {weekly_averages[week]:.2f} °C")

Daily Temperatures for the Month:
[32.01454575  2.42528999 29.36231092 16.9892643   7.75281512 29.87239021
 30.0322143  18.07230328 31.73727763  8.98826102 15.36653818 31.67919744
 11.76712989 26.71876219 18.62654158 15.78523447  5.5889813  17.86004299
  0.16991982 22.92578507  6.74534997 14.55482785  5.21133586 28.99533226
 11.29039803 24.17525588 19.68520806 19.886752   20.15477839 12.48824124]

Weekly Average Temperatures:
Week 1: 21.21 °C
Week 2: 20.62 °C
Week 3: 12.53 °C
Week 4: 17.69 °C
